# Tarea 2

**Nombre:** Luis Angel Tórtola  
**Carnet:** 25007713

---

In [173]:
from copy import deepcopy
import sympy as sym
import numpy as np 
import scipy

### Ejercicio 1

Considera el sistema de ecuaciones lineales:  

<br>

$x + 2y + z = 4$  
$2x− y + 3z = 1$  
$3x + y + 2z = 7$

<br>

**1)** Escribe el sistema en su forma matricial

In [174]:
A = np.array([[1, 2, 1],
              [2, -1, 3],
              [3, 1, 2]])

print(f'Shape: {A.shape}')
print(f'\nA:\n{A}')

Shape: (3, 3)

A:
[[ 1  2  1]
 [ 2 -1  3]
 [ 3  1  2]]



**2)** Escribe la matriz aumentada correspondiente al sistema


In [175]:
A_ = np.array([[1, 2, 1, 4],
               [2, -1, 3, 1],
               [3, 1, 2, 7]])

print(f'Shape: {A_.shape}')
print(f'\nA aumentada:\n{A_}')

Shape: (3, 4)

A aumentada:
[[ 1  2  1  4]
 [ 2 -1  3  1]
 [ 3  1  2  7]]


**3)** Utiliza scipy para calcular la rref de la matriz aumentada y resolver el
sistema de ecuaciones

In [176]:
B = np.array([4, 1, 7])
solution = scipy.linalg.solve(A, B)

print(f'Solución del sistema: {solution}')

Solución del sistema: [ 2.6  1.2 -1. ]


---
### Ejercicio 2

Dada la matriz:

<br>

$A = \begin{pmatrix} 1 & 3 & 5 \\ 2 & 4 & 6 \\ 0 & 1 & -1 \end{pmatrix}$  

<br>

**1)** Intercambia las dos filas  

**2)** Multiplica la primera fila por -3  

**3)** Suma 2 veces la segunda fila a la primera fila   

**4)** Escribe las matrices elementales asociadas a las operaciones de los incisos anteriores

In [177]:
matrices = []

A = np.array([[1, 3, 5], 
              [2, 4, 6],
              [0, 1, -1]])

matrices.append(deepcopy(A))

$R_1 \leftrightarrow R_2:$

In [178]:
temp = deepcopy(A[0])
A[0] = deepcopy(A[1])
A[1] = temp

matrices.append(deepcopy(A))

$R_1 = -3R_1:$

In [179]:
A[0] = -3 * A[0]

matrices.append(deepcopy(A))

$R_1 = R_1 + 2R_2:$

In [180]:
A[0] = A[0] + (2 * A[1])

matrices.append(deepcopy(A))

In [181]:
for matrix in matrices:
    print(f'\nA: \n{matrix}')


A: 
[[ 1  3  5]
 [ 2  4  6]
 [ 0  1 -1]]

A: 
[[ 2  4  6]
 [ 1  3  5]
 [ 0  1 -1]]

A: 
[[ -6 -12 -18]
 [  1   3   5]
 [  0   1  -1]]

A: 
[[-4 -6 -8]
 [ 1  3  5]
 [ 0  1 -1]]


---
### Ejercicio 3

Dada la matriz:

<br>

$A = \begin{pmatrix} 2 & -1 & 0 & 1 \\ 1 & 1 & 3 & 3 \\ 3 & 0 & -1 & 4 \end{pmatrix}$  

<br>

Resuelve el siguiente sistema usando Simpy y Numpy para encontrar su RREF

In [182]:
A = np.array([[2, -1, 0, 1],
              [1, 1, 3, 3],
              [3, 0, -1, 4]])

A_rref = sym.Matrix(A).rref()[0]

print('\nRREF de A:')
for i in range(0, 12, 4):
    print(A_rref[i:i+4])


RREF de A:
[1, 0, 0, 4/3]
[0, 1, 0, 5/3]
[0, 0, 1, 0]


Solución del sistema: $x = 1.\overline{33}, y = 1.\overline{66}, z = 0$

---
### Ejercicio 4

Utiliza el método de Gauss-Jordan para encontrar la forma escalonada reducida por filas de la siguiente matriz:

<br>

$A = \begin{pmatrix} 1 & -1 & 2 & 4 \\ 2 & -2 & 3 & 6 \\ -3 & 3 & -1 & -3 \end{pmatrix}$  

<br>

Describe cada paso y las operaciones elementales que realizadas...

In [183]:
A = np.array([[1, -1, 2, 4],
              [2, -2, 3, 6],
              [-3, 3, -1, -3]])

print(f'\nA: \n{A}')


A: 
[[ 1 -1  2  4]
 [ 2 -2  3  6]
 [-3  3 -1 -3]]


**Paso 1:** Restamos la primera fila multiplicada por 2, a la segunda fila.  

$R_2 = R_2 - 2R_1$

In [184]:
A[1] = A[1] - (2 * A[0])

print(f'\nA: \n{A}')


A: 
[[ 1 -1  2  4]
 [ 0  0 -1 -2]
 [-3  3 -1 -3]]


**Paso 2:** Sumamos la primera fila multiplicada por 3, a la tercera fila.  

$R_3 = R_3 - 3R_1$

In [185]:
A[2] = A[2] + (3 * A[0])

print(f'\nA: \n{A}')


A: 
[[ 1 -1  2  4]
 [ 0  0 -1 -2]
 [ 0  0  5  9]]


**Paso 3:** Multiplicamos la segunda fila por -1.  

$R_2 = -1R_2$

In [186]:
A[1] = -1 * A[1]

print(f'\nA: \n{A}')


A: 
[[ 1 -1  2  4]
 [ 0  0  1  2]
 [ 0  0  5  9]]


**Paso 4:** Restamos la segunda fila multiplicada por 2, a la primera fila.  

$R_1 = R_1 - 2R_2$

In [187]:
A[0] = A[0] - (2 * A[1])

print(f'\nA: \n{A}')


A: 
[[ 1 -1  0  0]
 [ 0  0  1  2]
 [ 0  0  5  9]]


**Paso 5:** Restamos la segunda fila multiplicada por 5, a la tercera fila.  

$R_3 = R_3 - 5R_2$

In [188]:
A[2] = A[2] - (5 * A[1])

print(f'\nA: \n{A}')


A: 
[[ 1 -1  0  0]
 [ 0  0  1  2]
 [ 0  0  0 -1]]


**Paso 6:** Multiplicamos la tercera fila por -1.  

$R_3 = -1R_3$

In [189]:
A[2] = -1 * A[2]

print(f'\nA: \n{A}')


A: 
[[ 1 -1  0  0]
 [ 0  0  1  2]
 [ 0  0  0  1]]


**Paso 7:** Restamos la tercera fila multiplicada por 2, a la segunda fila.  

$R_2 = R_2 - 2R_3$

In [190]:
A[1] = A[1] - (2 * A[2])

print(f'\nA: \n{A}')


A: 
[[ 1 -1  0  0]
 [ 0  0  1  0]
 [ 0  0  0  1]]


Hemos obtenido finalmente la RREF de $A$: <br><br>
$\begin{pmatrix} 1 & -1 & 0 & 0 \\ 0 & 0 & 1 & 0 \\ 0 & 0 & 0 &1 \end{pmatrix}$ 

---
### Ejercicio 5

Verifica si la siguiente matriz es invertible utilizando el método de RREF y,
si es así, calcula su inversa:

<br>

$A = \begin{pmatrix} 2 & 1 & 1 \\ 1 & 3 & 2 \\ 1 & 0 & 0 \end{pmatrix}$  

<br>

Explica el proceso y el significado de cada paso...

**Paso 1:** Para verificar si la matriz es invertible, debemos adjuntar a la derecha la matriz identidad, convertir la matriz original en una RREF y si ese resultado es una matriz identidad, entonces el resultado de la derecha será la matriz inversa.

Por lo tanto iniciamos agregando la matriz identidad a la derecha:

$A = \begin{pmatrix} 2 & 1 & 1 & | & 1 & 0 & 0  \\ 1 & 3 & 2 & | & 0 & 1 & 0 \\ 1 & 0 & 0 & | & 0 & 0 & 1 \end{pmatrix}$  

In [191]:
A = np.array([[2, 1, 1, 1, 0 ,0],
              [1, 3, 2, 0, 1, 0],
              [1, 0, 0, 0, 0, 1]])

print(f'Shape de A: {A.shape}')
print(f'\nA: \n{A}')

Shape de A: (3, 6)

A: 
[[2 1 1 1 0 0]
 [1 3 2 0 1 0]
 [1 0 0 0 0 1]]


**Paso 2:** Cambiamos la primera y tercera fila para tener un $1$ como pivote:

$R_1 \leftrightarrow R_3$  

In [192]:
temp = deepcopy(A[0])
A[0] = deepcopy(A[2])
A[2] = temp

print(f'A: \n{A}')

A: 
[[1 0 0 0 0 1]
 [1 3 2 0 1 0]
 [2 1 1 1 0 0]]


**Paso 3:** Limpiamos la columna del pivote, aplicando las siguientes operaciones:

$R_2 = R_2 - R_1$  
$R_3 = R_3 - 2R_1$

In [193]:
A[1] = A[1] - A[0] 
A[2] = A[2] - 2 * A[0]

print(f'A: \n{A}')

A: 
[[ 1  0  0  0  0  1]
 [ 0  3  2  0  1 -1]
 [ 0  1  1  1  0 -2]]


**Paso 4:** Restamos la tercera fila multiplicada por 3 a la segunda fila:

$R_2 = R_2 - 3R_3$

In [194]:
A[1] = A[1] - 3 * A[2]

print(f'A: \n{A}')

A: 
[[ 1  0  0  0  0  1]
 [ 0  0 -1 -3  1  5]
 [ 0  1  1  1  0 -2]]


**Paso 5:** Sumamos la tercera fila a la segunda fila:

$R_2 = R_2 + R_3$

In [195]:
A[1] = A[1] + A[2]

print(f'A: \n{A}')

A: 
[[ 1  0  0  0  0  1]
 [ 0  1  0 -2  1  3]
 [ 0  1  1  1  0 -2]]


**Paso 6:** Restamos la segunda fila a la tercera fila:

$R_3 = R_3 - R_2$

In [196]:
A[2] = A[2] - A[1]

print(f'A: \n{A}')

A: 
[[ 1  0  0  0  0  1]
 [ 0  1  0 -2  1  3]
 [ 0  0  1  3 -1 -5]]


Puesto que obtuvimos una matriz identidad del lado izquierdo, sabemos que $A$ es invertible y su inversa es la matriz resultante de la derecha. 

<br>

$A^{-1} = \begin{pmatrix} 0 & 0 & 1 \\ -2 & 1 & 3 \\ 3 & -1 & -5 \end{pmatrix}$ 

<br> 

---