# Tarea 1 

**Nombre:** Luis Angel Tórtola  
**Carnet:** 25007713

---

In [202]:
import numpy as np

### Ejercicio 1

Modifique el $T$ de forma $(2 \times 2 \times 2 \times 3)$ a forma $(8 \times 6)$.

In [203]:
T = np.array([[
        [
            [1, 3, 1],
            [-1, 5, 1]
        ],
        [
            [5, 0, 5],
            [-5, 0, 2]
        ]
    ],
    [
        [
            [0, 1, 2],
            [0, 1, 2]
        ],
        [
            [0, 0, 7],
            [0, 0, -7]
        ]
    ]])

In [204]:
try:
    T_reshaped = T.reshape(8, 6)
except:
    print(f'\nDicho reshape no es posible... ajustando a nueva forma (4x6):\n')
    T_reshaped = T.reshape(4, 6)

print(T_reshaped)


Dicho reshape no es posible... ajustando a nueva forma (4x6):

[[ 1  3  1 -1  5  1]
 [ 5  0  5 -5  0  2]
 [ 0  1  2  0  1  2]
 [ 0  0  7  0  0 -7]]


**Respuesta:** hacer un reshape a (8x6) no es posible debido a la cantidad de elementos en el tensor original. El tensor de $(2 \times 2 \times 2 \times 3)$ contiene 24 elementos. Un tensor de shape $(8 \times 6)$ requiere 48 elementos existentes. Como alternativa, se muestra un reshape de forma  $(4 \times 6)$.

---
### Ejercicio 2

Utilice la asociatividad en su forma básica para probar que las siguientes expresiones son equivalentes para vectores **a**, **b**, **c**:

$[a + (b + c)] + c = (a + b) + (c + c) = a + [(b + c) + c]$

In [205]:
a = np.array([7, 8, 9])
b = np.array([14, 16, 18])
c = np.array([21, 24, 27])

In [206]:
result_1 = (a + (b + c)) + c
result_2 = (a + b) + (c + c)
result_3 = a + ((b + c) + c)

In [207]:
# result_1, result_2, result_3
# result_1 == result_2

if np.array_equal(result_1, result_2) and np.array_equal(result_2, result_3):
    print('\nExiste asociatividad...')
else:
    print('\nNo existe asociatividad...')



Existe asociatividad...


**Respuesta:** se comprueba que existe asociatividad, evaluando cada expresión por separado y luego comparando los vetores resultantes.

---
### Ejercicio 3

Derive la desigualdad triangular:  $∥x + y∥≤∥x∥+ ∥y∥$  

para vectores **x**, **y**, **z** usando la desigualdad de Cauchy-Schwartz:  $⟨x |y⟩∥≤∥x∥∥y∥$

In [208]:
n = 5
x = np.array([7, 8, 10, 11, 17])
y = np.array([1, 14, 16, 33, 55])

x, y

(array([ 7,  8, 10, 11, 17]), array([ 1, 14, 16, 33, 55]))

In [209]:
norm_x_y = np.linalg.norm(x + y)
norm_x = np.linalg.norm(x)
norm_y = np.linalg.norm(y)
norms = norm_x + norm_y

print(f'||x + y|| = {round(norm_x_y, 4)}')
print(f'||x|| + ||y|| = {round(norms, 4)}')
print(f'\n||x + y|| <= ||x|| + ||y|| ... {norm_x_y <= norms}', )

||x + y|| = 91.3455
||x|| + ||y|| = 92.5396

||x + y|| <= ||x|| + ||y|| ... True


**Respuesta:** se comprueba la desigualdad triangular y la desigualdad Cauchy-Schwarz.

---
### Ejercicio 4

**Pregunta 1:**

¿Cuál es el shape resultante de multiplicar (*) dos arrays $A$ y $B$ si el array $A$ tiene shape $(1 \times 2 \times 1)$ y el array $B$ tiene shape $(1 \times 2)$? Justifique su respuesta.

In [210]:
A = np.array([[[3], [7]]])
B = np.array([[2, 9]])

print(f'Shape A: {A.shape}')
print(f'Shape B: {B.shape}')

result = np.matmul(A, B)
print(f'\nShape resultante: {result.shape}')
print(f'\nResultado:\n {result}')


Shape A: (1, 2, 1)
Shape B: (1, 2)

Shape resultante: (1, 2, 2)

Resultado:
 [[[ 6 27]
  [14 63]]]


**Respuesta:** el resultado tendrá un shape: $(1 \times 2 \times 2)$.

* En la primera dimensión a evaluar (primera desde la derecha), $A: 1$ y $B: 2$, por lo cual se hace broadcast y la dimensión resultante es 2.

*  En la segunda dimensión a evaluar (segunda desde la derecha), $A: 2$ y $B: 1$, por lo cual se hace broadcast y la dimensión resultante es 2.

*  En la última dimensión a evaluar (tercera desde la derecha), $A: 1$ y $B: \emptyset$, por lo cual implícitamente se toma como 1 la dimensión de $B$ y el resultante es igual 1.




**Pregunta 2:**

Si un array $C$ tiene shape $(3 \times 1)$ y un array $D$ tiene shape $(3 \times 4)$, ¿Cuál es el shape de $C + D$? Justifique su respuesta.

In [211]:
C = np.array([[3], [4], [5]])
D = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(f'Shape C: {C.shape}')
print(f'Shape D: {D.shape}')

result = C + D
print(f'\nShape resultante: {result.shape}')
print(f'\nResultado:\n {result}')

Shape C: (3, 1)
Shape D: (3, 4)

Shape resultante: (3, 4)

Resultado:
 [[ 4  5  6  7]
 [ 9 10 11 12]
 [14 15 16 17]]


**Respuesta:** el resultado tendrá un shape: $(3 \times 4)$.

* El broadcasting extiende la dimensión 1 del array $C$ para coincidir con el 4 de $D$, resultando en $4$.
* La segunda dimensión evaluada de $C$ y $D$ coincide en $3$, por lo cual no es necesario ningún ajuste y permite evaluar la suma.




**Pregunta 3:**

¿Por qué no es posible realizar una operación binaria entre un array $E$ con
shape $(5 \times 1)$ y un array $F$ con shape $(3,)$?

In [212]:
# Different shape
E = np.array([[0], [1], [1], [0], [1]])
F = np.array([0, 1, 1])

print(f'Shape E: {E.shape}')
print(f'Shape F: {F.shape}')

result_and = np.logical_and(E, F)
result_or = np.logical_or(E, F)

print(f'\nResult E AND F: \n {result_and}')
print(f'\nResult E OR F: \n {result_or}')

Shape E: (5, 1)
Shape F: (3,)

Result E AND F: 
 [[False False False]
 [False  True  True]
 [False  True  True]
 [False False False]
 [False  True  True]]

Result E OR F: 
 [[False  True  True]
 [ True  True  True]
 [ True  True  True]
 [False  True  True]
 [ True  True  True]]


In [213]:
# Same shape
F = np.array([0, 1, 1])
G = np.array([0, 1, 0])

print(f'Shape F: {F.shape}')
print(f'Shape G: {G.shape}')

result_and_same = np.logical_and(F, G)
result_or_same = np.logical_or(F, G)

print(f'\nResult F AND G: \n {result_and_same}')
print(f'\nResult F OR G: \n {result_or_same}')

Shape F: (3,)
Shape G: (3,)

Result F AND G: 
 [False  True False]

Result F OR G: 
 [False  True  True]


**Respuesta:** No es posible realizar operaciones binarias entre arrays de distinta shape. Como ejemplifica el código arriba, al tener una shape distinta se utilizará broadcasting y obtendremos un resultado aumentado, lo cual técnicamente se puede ejecutar pero no tienen ningún sentido dentro de la lógica binaria. 

Para realizar una operación binaria entre arrays, estos forzosamente deben tener el mismo shape para que la interpretación del resultado sea coherente. 

**Pregunta 4:**

Explique el proceso de broadcasting que ocurre cuando se suman dos arrays:
uno con shape $(3 \times 1 \times 6)$ y otro con shape $(1 \times 5 \times 1)$. ¿Cuál será el shape del
array resultante? Justifique su respuesta.

In [214]:
U = np.array([[[2, 2, 2, 2, 2, 2]], [[4, 4, 4, 4, 4, 4]], [[6, 6, 6, 6, 6, 6]]])
V = np.array([[[10], [20], [30], [40], [50]]])

print(f'Shape U: {U.shape}')
print(f'Shape V: {V.shape}')

result = U + V
print(f'\nShape resultante: {result.shape}')
print(f'\nResultado:\n {result}')

Shape U: (3, 1, 6)
Shape V: (1, 5, 1)

Shape resultante: (3, 5, 6)

Resultado:
 [[[12 12 12 12 12 12]
  [22 22 22 22 22 22]
  [32 32 32 32 32 32]
  [42 42 42 42 42 42]
  [52 52 52 52 52 52]]

 [[14 14 14 14 14 14]
  [24 24 24 24 24 24]
  [34 34 34 34 34 34]
  [44 44 44 44 44 44]
  [54 54 54 54 54 54]]

 [[16 16 16 16 16 16]
  [26 26 26 26 26 26]
  [36 36 36 36 36 36]
  [46 46 46 46 46 46]
  [56 56 56 56 56 56]]]


**Respuesta:** el resultado tendrá un shape: $(3 \times 5 \times 6)$.

Debido a las reglas de broadcasting, las dimensiones se extenderán, evaluándose desde la derecha.

* En la primera dimensión a evaluar (primera desde la derecha), $U: 6$ y $V: 1$, por lo cual se estira (*broadcast*) $V$ para coincidir con $U$ en tamaño $6$.

* En la primera dimensión a evaluar (primera desde la derecha), $U: 1$ y $V: 5$, por lo cual se estira (*broadcast*) $U$ para coincidir con $V$ en tamaño $5$.

* En la primera dimensión a evaluar (primera desde la derecha), $U: 3$ y $V: 1$, por lo cual se estira (*broadcast*) $V$ para coincidir con $U$ en tamaño $3$.


---
### Ejercicio 5

Calcule el producto de las matrices:  

$A = \begin{pmatrix} a_{1} & x \\ 0 & a_{2} \end{pmatrix}$
$B = \begin{pmatrix} b_{1} & 0 \\ 0 & b_{2} \end{pmatrix}$

Verifique si el producto es conmutativo comprobando si $AB = BA$ para cualesquiera valores $a_{1}, a_{2}, b_{1}, b_{2}, x ∈R$. Determine los valores de $x$ para los cuales el producto si conmuta.

In [215]:
from random import randint


def verify_commutativity(x_val: int):

    x = x_val
    a_1 = randint(2, 9)
    a_2 = a_1 + randint(1, 3)
    b_1 = randint(2, 9)
    b_2 = b_1 + randint(1, 3)

    A = np.array([[a_1, x], [0, a_2]])
    B = np.array([[b_1, 0], [0, b_2]])

    A_B = np.matmul(A, B)
    B_A = np.matmul(B, A)

    if np.array_equal(A_B, B_A):
        print(f'Con el valor x = {x}, la multiplicación SI es conmutativa.')
    else:
        print(f'Con el valor x = {x}, la multiplicación NO es conmutativa.')


for n in range(-5, 5):
    verify_commutativity(n)


Con el valor x = -5, la multiplicación NO es conmutativa.
Con el valor x = -4, la multiplicación NO es conmutativa.
Con el valor x = -3, la multiplicación NO es conmutativa.
Con el valor x = -2, la multiplicación NO es conmutativa.
Con el valor x = -1, la multiplicación NO es conmutativa.
Con el valor x = 0, la multiplicación SI es conmutativa.
Con el valor x = 1, la multiplicación NO es conmutativa.
Con el valor x = 2, la multiplicación NO es conmutativa.
Con el valor x = 3, la multiplicación NO es conmutativa.
Con el valor x = 4, la multiplicación NO es conmutativa.


**Respuesta:** demostramos que para cualesquiera valores $a_{1}, a_{2}, b_{1}, b_{2}$ la multiplicación de $A$ y $B$ será conmutativa solo cuando $x = 0$.

---
### Ejercicio 6

El outer product de **u** y **v**, donde:

$u = \begin{pmatrix} u_1 \\ u_2 \\ ... \\ u_m \end{pmatrix}, $
$v = \begin{pmatrix} v_1 \\ v_2 \\ ... \\ v_m \end{pmatrix}$

se define como la matriz: $A = u \cdot v^T$  

de dimensiones $m \times n$, o de forma equivalente: $a_{ij} = u_i v_j$

considere las siguientes matrices:

$A = \begin{pmatrix} 1 \\ 2 \\ 3 \\ ... \\ n \end{pmatrix}, $
$B = \begin{pmatrix} n & n - 1 & n - 2 & ... & 1 \end{pmatrix}$

In [216]:
n = 5

A = np.arange(1, n + 1).reshape(-1, 1)
B = np.arange(n, 0, -1)

print(f'A: \n{A} \nB: \n{B}')

A: 
[[1]
 [2]
 [3]
 [4]
 [5]] 
B: 
[5 4 3 2 1]


Calcule $ A \otimes B$:

In [217]:
U = np.outer(A, B)
print(f'U = \n {U}')

U = 
 [[ 5  4  3  2  1]
 [10  8  6  4  2]
 [15 12  9  6  3]
 [20 16 12  8  4]
 [25 20 15 10  5]]


Calcule la norma de cada fila de $A \otimes B$:

In [218]:
row_norms = np.linalg.norm(U, axis=1)

print(f'Norma de cada fila de U: {row_norms}')

Norma de cada fila de U: [ 7.41619849 14.83239697 22.24859546 29.66479395 37.08099244]


Calcule la norma de cada columna de $A \otimes B$:

In [219]:
col_norms = np.linalg.norm(U, axis=0)

print(f'Norma de cada columna de U: {col_norms}')

Norma de cada columna de U: [37.08099244 29.66479395 22.24859546 14.83239697  7.41619849]


---