# Tarea 3

**Nombre:** Luis Angel Tórtola  
**Carnet:** 25007713

---

In [56]:
import numpy as np
import sympy

### Ejercicio 1

Dados los vectores: 

<br>

$v_1 = \begin{bmatrix} 1 \\ 0 \\ 3 \\ 0  \\ 2 \\ 1 \end{bmatrix}, $
$v_2 = \begin{bmatrix} -1 \\ 0 \\ 0 \\ 1  \\ 2 \\ 1 \end{bmatrix}, $
$v_3 = \begin{bmatrix} -1 \\ 0 \\ 0 \\ -1  \\ 0 \\ -1 \end{bmatrix}, $
$v_4 = \begin{bmatrix} -1 \\ 0 \\ 0 \\ 0  \\ 1 \\ 0 \end{bmatrix}, $
$v_5 = \begin{bmatrix} 0 \\ 0 \\ 0 \\ 1  \\ 1 \\ 1 \end{bmatrix}, $
$v_6 = \begin{bmatrix} 1 \\ 0 \\ 3 \\ 1  \\ 3 \\ 2 \end{bmatrix} $

<br>

- Determine la dimensión de S el espacio generado por los $v_i$.
- Encuentre algunos $v_i$ que formen una base de $S$.
- Encuentre un conjunto de ecuaciones que determinen a $S$.

In [57]:
v1 = [ 1,  0,  3,  0,  2,  1]
v2 = [-1,  0,  0,  1,  2,  1]
v3 = [-1,  0,  0, -1,  0, -1]
v4 = [-1,  0,  0,  0,  1,  0]
v5 = [ 0,  0,  0,  1,  1,  1]
v6 = [ 1,  0,  3,  1,  3,  2]

M = np.column_stack((v1, v2, v3, v4, v5, v6))
print('Matriz M =')
print(M)

Matriz M =
[[ 1 -1 -1 -1  0  1]
 [ 0  0  0  0  0  0]
 [ 3  0  0  0  0  3]
 [ 0  1 -1  0  1  1]
 [ 2  2  0  1  1  3]
 [ 1  1 -1  0  1  2]]


In [58]:
rango_M = np.linalg.matrix_rank(M)
print('\nDimensión de S =', rango_M)


Dimensión de S = 3


In [59]:
M_sym = sympy.Matrix(M)
rref_M = M_sym.rref()
pivotes = rref_M[1]
print(f'\nRREF(M) = {rref_M[0]}')         
print(f'Columnas pivote = {pivotes}')


RREF(M) = Matrix([[1, 0, 0, 0, 0, 1], [0, 1, 0, 1/2, 1/2, 1/2], [0, 0, 1, 1/2, -1/2, -1/2], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0]])
Columnas pivote = (0, 1, 2)


In [60]:
print('\nBase de S a partir de columnas pivote:')
for p in pivotes:
    print(f'v{p+1} =', M[:, p])


Base de S a partir de columnas pivote:
v1 = [1 0 3 0 2 1]
v2 = [-1  0  0  1  2  1]
v3 = [-1  0  0 -1  0 -1]


In [61]:
left_null = sympy.Matrix(M).T.nullspace()

print('\nEcuaciones que definen S:')
for i, w in enumerate(left_null, 1):
    print(f'Ecuación {i}: {list(w)} · (x1, x2, x3, x4, x5, x6) = 0')


Ecuaciones que definen S:
Ecuación 1: [0, 1, 0, 0, 0, 0] · (x1, x2, x3, x4, x5, x6) = 0
Ecuación 2: [1, 0, -1, -1, 1, 0] · (x1, x2, x3, x4, x5, x6) = 0
Ecuación 3: [0, 0, -1/3, -1, 0, 1] · (x1, x2, x3, x4, x5, x6) = 0


---
### Ejercicio 2

Una población de aves se mueven de la región montañosa a la región de los lagos. La dinámica de los movimientos en un mes es la siguiente: 20% de la población de la montaña migra a los lagos y el resto se mantiene en la montaña. 25% de la población en el lago se mueve a la montaña y el resto se mantiene en el lago.

Escriba un operador lineal $T \begin{pmatrix} a \\ b \end{pmatrix}$ que describa la evolución de la
población de un mes al siguiente:
<br>

$T \begin{pmatrix} 1 \\ 0 \end{pmatrix} = \begin{pmatrix} 0.80 \\ 0.20 \end{pmatrix} $ <br><br> 
$T \begin{pmatrix} 0 \\ 1 \end{pmatrix} = \begin{pmatrix} 0.25 \\ 0.75 \end{pmatrix} $ <br><br>
$T \begin{pmatrix} a \\ b \end{pmatrix} = \begin{pmatrix} 0.80 & 0.25 \\ 0.20 & 0.75 \end{pmatrix} $

In [62]:
T = np.array([[0.8, 0.25], [0.2, 0.75]])
print(f'T = \n{T}')

T = 
[[0.8  0.25]
 [0.2  0.75]]


Suponga que la población de aves es de 800 en la montaña y 1200 en el lago, luego de un mes calcule la población en cada locación.
<br> 

$a = 800$  
$b = 1,200$

In [63]:
a_b = np.array([800, 1200])

result = np.matmul(T, a_b)
print(f'Población en montaña: {int(result[0])}, lago: {int(result[1])}')

Población en montaña: 940, lago: 1060


---
### Ejercicio 3

Dado el con junto de vectores $B = {(1,−1, 0), (2, 2, 0), (0, 0, 3)}$, verifica si forma una base ortogonal. Si no es así, identifique qué pares de vectores no son ortogonales.

In [70]:
v1 = np.array([ 1, -1, 0])
v2 = np.array([ 2,  2, 0])
v3 = np.array([ 0,  0, 3])

dot_1 = np.dot(v1, v3)
dot_2 = np.dot(v1, v2)
dot_3 = np.dot(v2, v3)

if dot_1 == 0 and dot_2 ==0 and dot_3 == 0:
    print('\nLos tres vectores son ortogonales...')


Los tres vectores son ortogonales...


Los tres vectores prueban ser ortogonales, por lo cual generan una base en $\mathbb{R}^3$.

---
### Ejercicio 4

Considera el subespacio generado por $C= {(2/5, 3/5, 0), (0, 0,−1)}$.

• Utilice la ecuación $Q \times Q^T$ para encontrar la representación matricial del operador de proyección.

• Calcula la proyección ortogonal del vector $p = (1, 1, 1)$ sobre este subespacio y determina la distancia de $p$ al subespacio.

In [65]:
c1 = np.array([2/5, 3/5, 0])
c2 = np.array([0, 0, -1])

# Normalizar
norm_c1 = np.linalg.norm(c1)
c1_n = c1 / norm_c1
norm_c2 = np.linalg.norm(c2)
c2_n = c2 / norm_c2

Q = np.column_stack((c1_n, c2_n))
P = np.matmul(Q, Q.T)

p = np.array([1,1,1], dtype=float)
p_proj = np.matmul(P, p)

distancia = np.linalg.norm(p - p_proj)

print(f'\nMatriz de proyección P:\n {P}')
print(f'\nProyección de p sobre el subespacio = {p_proj} ')
print(f'Distancia de p al subespacio = {distancia}')


Matriz de proyección P:
 [[0.30769231 0.46153846 0.        ]
 [0.46153846 0.69230769 0.        ]
 [0.         0.         1.        ]]

Proyección de p sobre el subespacio = [0.76923077 1.15384615 1.        ] 
Distancia de p al subespacio = 0.2773500981126146


--- 
### Ejercicio 5

Considere el tensor:

$ T  = \begin{bmatrix} \begin{bmatrix} 4 & 2 \\ 2 & 2 \end{bmatrix} & \begin{bmatrix} 3 & 2 \\ 2 & 4 \end{bmatrix} \\ \begin{bmatrix} 7 & 3 \\ 2 & 3 \end{bmatrix} & \begin{bmatrix} 4 & 3 \\ 5 & 1 \end{bmatrix} \end{bmatrix} $

Donde $T_{ijkl}$ representa la venta ($l = 0$) y existencia en bodega ($l=1$), de tractores, en las locaciones ($i = 0$ en Guatemala, $i = 1$ en el exterior), $j = 0, 1$ las dos salas de ventas, $k = 0$ modelos ligeros, $k = 1$ modelos pesados.

Calcule la siguiente y describa que representa:  

$ \sum\limits_{i=0}^{1} \sum\limits_{j=0}^{1} \sum\limits_{k=0}^{1} T_{ijk0} $ 

In [66]:
T = np.array([
    [
      [ [4, 2], [3, 2] ],
      [ [2, 2], [2, 4] ]
    ],
    [
      [ [7, 3], [4, 3] ],
      [ [2, 3], [5, 1] ]
    ]
])

sales = T[:,:,:,0].sum()
print(f'Suma total T_ijk0 = {sales}')

Suma total T_ijk0 = 29


$ \sum\limits_{i=0}^{1} \sum\limits_{j=0}^{1} \sum\limits_{k=0}^{1} T_{ijk0}:$ representa las ventas totales; todas las locaciones, salas de venta y modelos.

---
### Ejercicio 6

Considere el sistema de ecuaciones siguiente:

$ x + y − z + w = 1 $  
$ −x − 2y + z + 2w = 3 $  
$ 2x + 3y − 2z − w = −2 $

Escriba el la representación del sistema como una matriz aumentada: 

$A = \begin{pmatrix} 1 & 1 & -1 & 1 & | & 1 \\ -1 & -2 & 1 & 2 & | & 3 \\ 2 & 3 & -2 & -1 & | & -2 \end{pmatrix}$  


In [67]:
A = np.array([
    [1,  1, -1,  1,  1],
    [-1, -2,  1,  2,  3],
    [2,  3, -2, -1, -2]
])

print(f'A = \n{A}')

A = 
[[ 1  1 -1  1  1]
 [-1 -2  1  2  3]
 [ 2  3 -2 -1 -2]]


Calcule la rref de la matriz anterior. 

Podemos obtener la RREF aplicando las siguientes operaciones:

$R_2 = R_2 + R_1$  
$R_3 = R_3 - 2R_1$  
$R_1 = R_1 + R_2$  
$R_3 = R_3 + R_2$  
$R_2 = -1R_2$  

In [68]:
A_ = sympy.Matrix(A)
A_rref = A_.rref()
print(f'RREF: \n{A_rref[0]}')

RREF: 
Matrix([[1, 0, -1, 4, 5], [0, 1, 0, -3, -4], [0, 0, 0, 0, 0]])


Para las primeras dos operaciones entre filas realizadas anteriormente, escriba las matrices elementales asociadas:

<br> 

$E_1 = \begin{pmatrix} 1 & 0 & 0 \\ 1 & 1 & 0 \\ 0 & 0 & 1 \end{pmatrix}$  <br><br>
$E_2 = \begin{pmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ -2 & 0 & 1 \end{pmatrix}$  

Encuentre la solución del sistema de ecuaciones:

In [69]:
x, y, z, w = sympy.symbols('x y z w')

solution = sympy.solve([
    x + y - z + w - 1,
    -x - 2*y + z + 2*w - 3,
    2*x + 3*y - 2*z - w +2
], [x, y, z, w], dict=True)

print(f'Solución: {solution}')

Solución: [{x: -4*w + z + 5, y: 3*w - 4}]


Dada la RREF logramos saber que:  

$x - z + 4w = 5$  
$y - 3w = -4$  

$z = \lambda, w = \mu $  

Despejamos:

$ x = 5 + \lambda - 4\mu $  
$ y = - 4 + 3\mu $

Con lo cual:

$ x = 5 + \lambda - 4\mu $  
$ y = -4 + 3\mu  $   
$ z = \lambda  $   
$ w = \mu  $   

**Respuesta:** 
<br><br>
$ (x, y, z, w) = (5, -4, 0, 0) + \lambda(1, 0, 1, 0) + \mu(-4. 3, 0, 1) $  

Donde $ \lambda, \mu \in \mathbb{R} $ y son los parámetros libres. Por lo cual generan una hiperplano en $\mathbb{R}^4 $ como solución al sistema. 

---






