# Laboratorio 2

**Nombre:** Luis Angel Tórtola  
**Carnet:** 25007713

---


In [3]:
import numpy as np
from copy import deepcopy

# Operaciones Elementales y Matrices Escalonadas

## Operaciones Elementales por Filas

Las operaciones elementales por filas son transformaciones que se pueden
aplicar a las filas de una matriz sin cambiar el conjunto de soluciones
del sistema de ecuaciones. Son:

1.  **Intercambio de Filas:** Cambiar de posición dos filas de la
    matriz.
2.  **Multiplicación por un Escalar:** Multiplicar todos los elementos
    de una fila por un número distinto de cero.
3.  **Suma de un Múltiplo de una Fila a Otra Fila:** Sumar a una fila un
    múltiplo de otra fila.

Estas operaciones se utilizan para simplificar el sistema de ecuaciones
hasta llegar a una forma más fácilmente resoluble.

## Intercambio de Filas

Escriba una función en Python que reciba un arreglo de Numpy los indices $i$, $j$ de las filas a intercambiar, intercambie las filas en el arreglo de Numpy y retorne una matriz elemental que represente la operación realizada.

In [4]:
def swap(A, i, j):
    
    temp_row = deepcopy(A[i])
    A[i] = A[j]
    A[j] = temp_row
    return A

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(f'\nBefore:\n {A}\n')
print('After: \n', swap(A, 0, 2))


Before:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

After: 
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


## Multiplicación por un Escalar

Escriba una función que reciba un arreglo de Numpy $A$, el indice de la fila $i$, un escalar $a$, multiplique la fila $i$ de $A$ por $a$ y retorne la matriz elemental correspondiente. 

In [5]:
def multiply_row(A, i, a):
    
    A[i] = [num * a for num in A[i]]    
    return A

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(f'\nBefore:\n {A}\n')
print('After: \n', multiply_row(A, 1, 2))


Before:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

After: 
 [[ 1  2  3]
 [ 8 10 12]
 [ 7  8  9]]


## Suma de un Múltiplo de una Fila a Otra Fila:

Implemente la operación elemental de tipo 3, sumar una fila por un escalar a otra. En este caso recibe como input: $A$, $i$, $j$, $\alpha$.
Para la matriz $A$, sume a la fila $i$ la fila $j$ multiplicada por $\alpha$. Retorne la matriz elemental asociada.


In [6]:
def add_row(A, i, j, alpha):
    
    temp_row = deepcopy(A[j])
    temp_row = [num * alpha for num in temp_row]
    A[i] = [x + y for x, y in zip(A[i], temp_row)]
    return A

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(f'\nBefore:\n {A}\n')
print('After: \n', add_row(A, 1, 0, -4))


Before:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

After: 
 [[ 1  2  3]
 [ 0 -3 -6]
 [ 7  8  9]]




## Forma Escalonada por Filas Reducida

La forma escalonada por filas reducida es un refinamiento de la forma
escalonada por filas en el que además de las propiedades anteriores:

1.  El pivote de cada fila es 1.
2.  Cada pivote es el único número distinto de cero en su columna.



In [7]:
def next_pivot(A, start_row, start_col):
    '''
    Dada una matriz A donde se han selecionado pivotes en las filas hasta start_row -1, 
    y hasta la columna start_col-1.
    Lo que significa que los elementos de las filas pivote son 0. Encuentre la posición del siguiente pivote.
    '''

    rows, cols = A.shape

    for col in range(start_col, cols):
        for row in range(start_row, rows):
            if A[row, col] != 0:
                return row, col
            
    return row, col


def clean_column(A, pivot_row, pivot_column):
    '''
    De la matriz A, usando como pivote la pivot_row, luego de convertirla a 1,
    convierta en 0 todas las entradas, diferentes a la pivot_row,
    de la pivot_column.

    Retorne un arreglo con todas las matrices elementales que representan
    las operaciones elementales realizadas.
    '''

    rows = A.shape[0]
    elementals = []

    # Convertir pivote a 1
    pivot_element = A[pivot_row, pivot_column]
    # A[pivot_row] = A[pivot_row] / pivot_element
    # print(f'Pivot element: {pivot_element}')
    A = multiply_row(A, pivot_row, 1/pivot_element)
    elementals.append(deepcopy(A))

    # Convertir a 0s el resto de la columna
    for row in range(rows):
        if row != pivot_row:
            factor = A[row, pivot_column]
            # A[row] = A[row] - factor * A[pivot_row]
            A = add_row(A, row, pivot_row, factor * -1)
            elementals.append(deepcopy(A))

    return elementals


A = np.array([
    [1, 2, 1, 2, 4, 5],
    [0, 0, 0, 0, 3, 3],
    [0, 0, 0, 8, 24, 16]
], dtype = float)

# Expected i = 2, j = 3
i, j = next_pivot(A, 1, 1)
# print(i, j)

# clean_column(A, i, j)
# print(clean_column(A, i, j))
print(clean_column(A, i, j)[-1])

[[ 1.  2.  1.  0. -2.  1.]
 [ 0.  0.  0.  0.  3.  3.]
 [ 0.  0.  0.  1.  3.  2.]]


## RREF

Escriba una función que reciba una matriz rectangular $A$.

- Compute la forma escalonada reducida por filas para $A$.
- Retorne un tensor de $(M, n, n)$ donde $n$ es el número de filas de $A$ tal que $E[-i, :, :]$ contenga la matriz elemental asociada a la $i$-esima operación elemental.

Finalmente verifique que el producto de matrices elementales por la izquierda con $A$ es la rref.

In [8]:
def rref(A):

    rows = A.shape[0]
    current_row = 0
    current_col = 0
    elementals = [deepcopy(A)]
    
    while current_row < rows:
        
        pivot_row, pivot_col = next_pivot(A, current_row, current_col)
        # print(f'Pivot: {(pivot_row, pivot_col)}')
        clean_column(A, pivot_row, pivot_col)
        swap(A, current_row, pivot_row)
        elementals.append(deepcopy(A))
        current_row += 1

        # Termina si quedan filas de 0s abajo
        if np.all(A[current_row:] == 0):
            break

    return elementals


def check_rref(A):
    '''
    Dada la matriz A, retorne True si está en forma escalonada reducida por filas
    y False en caso contrario.
    '''

    rows, cols = A.shape
    pivot_col = -1

    for row in range(rows):
        # Encontrar primer elemento distinto a 0
        for col in range(cols):
            if A[row, col] != 0:
                if A[row, col] != 1:
                    return False
                pivot_col = col
                break

        # Verificar resto de elementos en la columna
        for r in range(rows):
            if r != row and A[r, pivot_col] != 0:
                return False

        # Verificar que elementos a la izquierda y hacia abajo sean 0
        if any(A[row, :pivot_col] != 0):
            return False
        
        # Break si solo quedan filas de 0s abajo
        if np.all(A[row + 1:] == 0):
            break

    return True


In [9]:
'''
Testing de métodos RREF.
'''

A = np.array([
    [1, 2, 1, 2, 4, 5],
    [0, 0, 0, 0, 3, 3],
    [0, 0, 0, 8, 24, 16]
], dtype = float)

result = rref(A)

for matrix in result:
    print(matrix, '\n')
    print(f'RREF: {check_rref(matrix)} \n')


[[ 1.  2.  1.  2.  4.  5.]
 [ 0.  0.  0.  0.  3.  3.]
 [ 0.  0.  0.  8. 24. 16.]] 

RREF: False 

[[ 1.  2.  1.  2.  4.  5.]
 [ 0.  0.  0.  0.  3.  3.]
 [ 0.  0.  0.  8. 24. 16.]] 

RREF: False 

[[ 1.  2.  1.  0. -2.  1.]
 [ 0.  0.  0.  1.  3.  2.]
 [ 0.  0.  0.  0.  3.  3.]] 

RREF: False 

[[ 1.  2.  1.  0.  0.  3.]
 [ 0.  0.  0.  1.  0. -1.]
 [ 0.  0.  0.  0.  1.  1.]] 

RREF: True 



Pruebe el método implenetado anteriormente con la matriz:

$$\begin{equation}
B = 
\begin{bmatrix}
1 & 0 & 2 & 2 & 6 & 2 & 0 \\
1 & 0 & 2 & 2 & 6 & 2 & 0 \\
-1 & 0 & -2 & 1 & 3 & 1 & 0 \\
2 & 0 & 4 & 3 & 9 & 3 & 1
\end{bmatrix}
\end{equation}$$

en Numpy

-   Realice las operaciones elementales necesarias para convertirla en
    una rref.
-   Guarde las matrices elementales asociadas en un tensor de Numpy.
-   Verifique que el producto de matrices elementales con la matriz B es
    igual a la rref.

In [10]:
B = np.array([
    [1, 0, 2, 2, 6, 2, 0],
    [1, 0, 2, 2, 6, 2, 0],
    [-1, 0, -2, 1, 3, 1, 0],
    [2, 0, 4, 3, 9, 3, 1]
], dtype = float)


result = rref(deepcopy(B))

for matrix in result:
    print(matrix, '\n')
    print(f'RREF: {check_rref(matrix)} \n')

[[ 1.  0.  2.  2.  6.  2.  0.]
 [ 1.  0.  2.  2.  6.  2.  0.]
 [-1.  0. -2.  1.  3.  1.  0.]
 [ 2.  0.  4.  3.  9.  3.  1.]] 

RREF: False 

[[ 1.  0.  2.  2.  6.  2.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  3.  9.  3.  0.]
 [ 0.  0.  0. -1. -3. -1.  1.]] 

RREF: False 

[[1. 0. 2. 0. 0. 0. 0.]
 [0. 0. 0. 1. 3. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]] 

RREF: False 

[[1. 0. 2. 0. 0. 0. 0.]
 [0. 0. 0. 1. 3. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]] 

RREF: True 



In [11]:
# TODO: verificacion final

for matrix in result[:-1]:
    B = B * matrix

print(B)

[[ 1.  0. 16.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -0. -0. -0.  1.]]
