# Tarea 1 

**Nombre:** Luis Angel Tórtola  
**Carnet:** 25007713

---


## Instrucciones

En las siguientes celdas se tienen datos generados sintéticamente que representan las ventas de 8 productos en varias tiendas ubicadas en 10 departamentos de Guatemala y en 10 almacenes. Los datos están representados por una fila que proviene de un tensor de la siguiente forma:

$$   a_{ijk} = \text{Ventas del Producto}_i \text{ en el Departamento}_j $$

Si $k = 0$, es en una tienda; si $k = 1$, es en un almacén. Adicionalmente, se cuenta con el costo y el precio de venta de cada uno de los productos. Tome en cuenta que el costo de cada producto varía según sea una tienda o un almacén, y también depende del lugar. El tensor de precios está representado por:
$$ b_{ijk} = \text{Precios del Producto}_i \text{ en el Departamento}_j $$

1. Re-construya el tensor de ventas.
2. Construya un vector columna con el total de ventas de cada producto vendidos en todas las tiendas.
 - Calcule usando suma de ejes.
 - Calcule como un producto matricial usando np.ones(...).
 - Despliegue los resultados por producto.
3. Construya una matriz de precios $p_{ik}$ con los datos proporcionados y utilicela para calcular el costo total por departamento.
4. Calcule el total de ventas por producto utilizando los datos de los precios de venta.
5. Calcule el total de ganancias por producto.
6. Calcule el total de ganancias por departamento.
5. Calcule el total de ganancias.

Escriba cada una de las soluciones en dos celdas una en markdown con la ecuación correspondiente e.g. total de ventas $\sum_{i,j,k} a_{ijk}$. Y una de código con la implementación en Numpy.

In [1]:
import numpy as np


# Ventas
ventas = np.array(
     [18, 13, 26, 19, 28, 12, 22, 8, 9, 28, 24, 25, 27, 19, 21, 15,
      22, 22, 7, 32, 6, 17, 16, 6, 34, 15, 26, 12, 6, 10, 11, 34,
      11, 6, 20, 34, 14, 13, 21, 31, 10, 26, 16, 27, 27, 24, 15,
      14, 6, 34, 33, 20, 24, 32, 13, 29, 8, 31, 13, 14, 23, 11, 8,
      34, 21, 22, 6, 23, 30, 22, 11, 23, 34, 19, 28, 28, 23, 22, 17,
      7, 10, 21, 11, 17, 9, 31, 24, 6, 33, 18, 30, 5, 25, 19, 5, 23,
      27, 23, 7, 11, 26, 33, 16, 26, 30, 11, 17, 21, 29, 21, 11, 6,
      31, 32, 21, 19, 5, 16, 5, 31, 30, 15, 25, 11, 10, 26, 30, 20, 
      12, 5, 26, 7, 33, 20, 20, 14, 28, 6, 9, 9, 21, 15, 5, 13, 27, 
      15, 29, 18, 25, 22, 5, 15, 11, 27, 16, 19, 20, 26, 12, 34])

# Costos
costos = np.array(
  [
    [ [0.51, 0.98, ],[0.56, 0.91, ],[0.38, 0.97, ],[0.44, 0.87, ],[0.65, 0.9, ],[0.36, 0.55, ],[0.4, 0.76, ],[0.46, 0.61, ],[0.58, 0.85, ],[0.64, 0.65, ], ],
    [ [0.56, 0.6, ],[0.54, 0.51, ],[0.46, 0.58, ],[0.69, 0.48, ],[0.57, 0.78, ],[0.62, 0.65, ],[0.6, 0.76, ],[0.65, 0.52, ],[0.72, 0.74, ],[0.58, 0.64, ], ],
    [ [0.42, 0.84, ],[0.47, 0.64, ],[0.32, 0.51, ],[0.33, 0.52, ],[0.39, 0.68, ],[0.39, 0.84, ],[0.45, 0.8, ],[0.52, 0.83, ],[0.36, 0.68, ],[0.49, 0.66, ], ],
    [ [0.47, 0.67, ],[0.63, 0.54, ],[0.43, 0.58, ],[0.41, 0.5, ],[0.53, 0.47, ],[0.48, 0.62, ],[0.54, 0.69, ],[0.57, 0.51, ],[0.38, 0.42, ],[0.58, 0.74, ], ],
    [ [0.93, 1.4, ],[1.28, 1.24, ],[1.28, 1.38, ],[0.89, 1.61, ],[1.05, 1.34, ],[1.26, 1.17, ],[1.02, 1.5, ],[1.05, 1.75, ],[1.11, 1.27, ],[1.34, 1.51, ], ],
    [ [1.24, 1.36, ],[1.47, 1.54, ],[1.38, 1.06, ],[1.13, 1.77, ],[1.12, 1.76, ],[1.1, 1.34, ],[1.1, 1.08, ],[0.96, 1.84, ],[1.31, 1.49, ],[1.02, 1.85, ], ],
    [ [0.89, 1.26, ],[0.82, 0.79, ],[0.72, 0.97, ],[0.97, 1.28, ],[0.96, 1.2, ],[0.86, 0.74, ],[0.94, 1.27, ],[0.98, 1.05, ],[0.61, 1.0, ],[0.63, 1.26, ], ],
    [ [0.07, 0.13, ],[0.1, 0.12, ],[0.08, 0.12, ],[0.09, 0.19, ],[0.06, 0.13, ],[0.08, 0.15, ],[0.1, 0.12, ],[0.09, 0.15, ],[0.08, 0.12, ],[0.11, 0.2, ], ]
  ]
)

# Indice departamentos
index_depto = { 0: "Guatemala", 1: "Huehuetenango", 2: "Alta Verapaz", 3: "Quiché",
   4: "Escuintla", 5: "Jutiapa", 6: "San Marcos", 7: "Suchitepéquez", 8: "Chimaltenango",
   9: "Jalapa" }

# Indice productos
index_prod = {'frijol': 4, 'maíz': 2, 'aceite': 1, 'frituras': 7, 'pasta': 0, 'agua': 3, 'arina maíz': 6, 'arina trigo': 5}

# Precios de venta por producto -- son iguales en todas los departamentos
precio_venta_almacen = {'pasta': 1.5, 'agua': 1.5, 'arina maíz': 2.25, 'arina trigo': 3.75, 'frijol': 3.25, 'maíz': 1.25, 'aceite': 1.75, 'frituras': 0.25 }

precio_venta_tienda = {'pasta': 2.25, 'agua': 1.75, 'arina maíz': 3.0, 'arina trigo': 4.25, 'frijol': 4.00, 'maíz': 2.00, 'aceite': 2.00, 'frituras': 0.45 }


# Resolución
---



**1) Re-construya el tensor de ventas.**

Convertimos el tensor de ventas en la forma $(8 \times 10 \times 2)$.

In [2]:
# i productos, j departamento, k tipo locación
ventas = ventas.reshape(8, 10, 2)
print(f'Shape nueva: {ventas.shape}')
print(f'\nPrimer elemento (producto):\n {ventas[0]}')


Shape nueva: (8, 10, 2)

Primer elemento (producto):
 [[18 13]
 [26 19]
 [28 12]
 [22  8]
 [ 9 28]
 [24 25]
 [27 19]
 [21 15]
 [22 22]
 [ 7 32]]


**2) Construya un vector columna con el total de ventas de cada producto vendidos en todas las tiendas.**  
<br>
2.1) Calcule usando suma de ejes.


In [3]:
ventas_columna = np.sum(ventas[:, :, 0], axis=1).reshape(-1, 1)
#print(np.transpose(ventas_columna))
print(ventas_columna)

[[204]
 [165]
 [165]
 [201]
 [181]
 [191]
 [223]
 [171]]


2.2) Calcule como un producto matricial usando np.ones(...).  

In [4]:
num_departamentos = ventas.shape[1]

vector_unos = np.ones((num_departamentos, 1)) # Crear un vector de unos para sumar por producto

ventas_tiendas_mat = np.dot(ventas[:, :, 0], vector_unos)

print(ventas_tiendas_mat)


[[204.]
 [165.]
 [165.]
 [201.]
 [181.]
 [191.]
 [223.]
 [171.]]


2.3) Despliegue los resultados por producto.

In [5]:
print('Total vendidos por producto: \n')

for key, value in index_prod.items(): 
    # print(key, value)
    print(f'{key.capitalize()}: {ventas_columna[value][0]}')


Total vendidos por producto: 

Frijol: 181
Maíz: 165
Aceite: 165
Frituras: 171
Pasta: 204
Agua: 201
Arina maíz: 223
Arina trigo: 191


**3. Construya una matriz de precios $p_{ik}$ con los datos proporcionados y utilicela para calcular el costo total por departamento.**

In [6]:
productos = list(precio_venta_tienda.keys())  # Lista de productos en el mismo orden

# Matriz de precios vacía de (8x2)
precios = np.zeros((8, 2))
# precios

# Llenar matriz con los precios en los diccionarios
for i, producto in enumerate(productos):
    precios[i, 0] = precio_venta_tienda[producto] 
    precios[i, 1] = precio_venta_almacen[producto]

# print(precios.shape)
print(precios)


[[2.25 1.5 ]
 [1.75 1.5 ]
 [3.   2.25]
 [4.25 3.75]
 [4.   3.25]
 [2.   1.25]
 [2.   1.75]
 [0.45 0.25]]


**4. Calcule el total de ventas por producto utilizando los datos de los precios de venta.**


In [7]:
ventas_producto = np.sum(ventas, axis=1)
# ventas_producto
total_ventas_por_producto_y_locacion = (ventas_producto * precios)
total_ventas_por_producto_y_locacion
total_ventas_por_producto = np.sum(total_ventas_por_producto_y_locacion, axis=1)
total_ventas_por_producto

array([ 748.5 ,  555.75, 1059.75, 1645.5 , 1289.5 ,  652.  ,  678.75,
        127.95])

In [8]:
print('Ventas por producto: \n')
for key, value in index_prod.items(): 
    print(f'{key.capitalize()}: {total_ventas_por_producto[value]}')

Ventas por producto: 

Frijol: 1289.5
Maíz: 1059.75
Aceite: 555.75
Frituras: 127.95
Pasta: 748.5
Agua: 1645.5
Arina maíz: 678.75
Arina trigo: 652.0


**5. Calcule el total de ganancias por producto.**


In [9]:
ventas_producto = np.sum(ventas, axis=1)

# costos.shape
costos_totales = ventas * costos

costos_producto = np.sum(costos_totales, axis=1)
# costos_producto

total_ventas_por_producto_y_locacion = (ventas_producto * precios)
# total_ventas_por_producto_y_locacion

ganancias_por_producto_y_locacion = total_ventas_por_producto_y_locacion - costos_producto
ganancias_por_producto_y_locacion

total_ganancias_por_producto = np.sum(ganancias_por_producto_y_locacion, axis=1)
total_ganancias_por_producto

array([ 501.58,  348.75,  813.87, 1427.66,  843.23,   95.68,  340.97,
         84.  ])

In [10]:
print('Ganancias por producto: \n')
for key, value in index_prod.items(): 
    print(f'{key.capitalize()}: {total_ganancias_por_producto[value]}')

Ganancias por producto: 

Frijol: 843.23
Maíz: 813.87
Aceite: 348.75
Frituras: 84.0
Pasta: 501.58
Agua: 1427.66
Arina maíz: 340.97
Arina trigo: 95.67999999999998


**6. Calcule el total de ganancias por departamento.**

In [11]:
# Costos por departamento
costos_totales = ventas * costos
# costos_totales
costos_depto = np.sum(costos_totales, axis=(0, 2))
# costos_depto.shape
# costos_depto

# Total ventas (ingresos) por departamento
precios_full = np.broadcast_to(np.expand_dims(precios, axis=1), (8, 10, 2))
total_ventas = ventas * precios_full
total_ventas_depto = np.sum(total_ventas, axis=(0, 2))
# total_ventas_depto.shape
# total_ventas_depto

ganancias_por_depto = total_ventas_depto - costos_depto
ganancias_por_depto.shape
ganancias_por_depto

array([379.91, 411.03, 528.62, 386.89, 472.44, 480.25, 566.01, 471.18,
       484.78, 274.63])

In [12]:
print('Ganancias por departamento: \n')
for key, value in index_depto.items(): 
    print(f'{value.capitalize()}: {ganancias_por_depto[key]}')

Ganancias por departamento: 

Guatemala: 379.9100000000001
Huehuetenango: 411.03
Alta verapaz: 528.62
Quiché: 386.89
Escuintla: 472.43999999999994
Jutiapa: 480.25
San marcos: 566.01
Suchitepéquez: 471.18000000000006
Chimaltenango: 484.78
Jalapa: 274.63


**7. Calcule el total de ganancias.**

In [13]:
total_ganancias = total_ganancias_por_producto.sum()

print(f'Total ganancias: {total_ganancias}')

Total ganancias: 4455.74
